/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.interfacetest;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.io.File;
import javax.swing.JPanel;

/**
 *
 * @author avery
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        
        try{
            // Import fonts
            File importTitleFont = new File("src/main/resources/Fonts/Anton-Regular.ttf");
            File importBodyFont = new File("src/main/resources/Fonts/MajorMonoDisplay-Regular.ttf");
            File importAccentFont = new File("src/main/resources/Fonts/OpenSans-Regular.ttf");
            
            // Assign fonts to variables, set font size
            Font titleFont = Font.createFont(Font.TRUETYPE_FONT, importTitleFont).deriveFont(60f);
            Font bodyFont = Font.createFont(Font.TRUETYPE_FONT, importBodyFont).deriveFont(18f);
            Font accentFont = Font.createFont(Font.TRUETYPE_FONT, importAccentFont).deriveFont(14f);
            
            // Set font for UI
            eduSyncTitle.setFont(titleFont);
            eduSyncSlogan.setFont(bodyFont);
            emailLabel.setFont(accentFont);
            passLabel.setFont(accentFont);
            
            loginButton.setFont(Font.createFont(Font.TRUETYPE_FONT, importAccentFont).deriveFont(24f));
            
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        eduSyncTitle = new javax.swing.JLabel();
        eduSyncSlogan = new javax.swing.JLabel();
        ccstLogo = new javax.swing.JLabel();
        sidePanelBgImage = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        userIcon = new javax.swing.JLabel();
        passPanel = new RoundedPanel(15,new Color(38, 55, 120));
        smallKeyIcon = new javax.swing.JLabel();
        passPaneSeparator = new javax.swing.JLabel();
        passField = new javax.swing.JPasswordField();
        emailPanel = new RoundedPanel(15,new Color(38, 55, 120));
        smallUserIcon = new javax.swing.JLabel();
        emailPaneSeparator = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        passLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EduSYnc ");
        setResizable(false);

        bgPanel.setBackground(new java.awt.Color(51, 51, 51));
        bgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setOpaque(false);
        sidePanel.setPreferredSize(new java.awt.Dimension(510, 570));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eduSyncTitle.setFont(new java.awt.Font("Anton", 0, 60)); // NOI18N
        eduSyncTitle.setForeground(new java.awt.Color(255, 255, 255));
        eduSyncTitle.setText("EduSync");
        sidePanel.add(eduSyncTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        eduSyncSlogan.setFont(new java.awt.Font("Major Mono Display", 0, 18)); // NOI18N
        eduSyncSlogan.setForeground(new java.awt.Color(255, 255, 255));
        eduSyncSlogan.setText("<html>\ntrack academic progress<br> seamlessly\n</html>");
        sidePanel.add(eduSyncSlogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        ccstLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CCSTLOGOFINAL.png"))); // NOI18N
        sidePanel.add(ccstLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 220, -1));

        sidePanelBgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg2.png"))); // NOI18N
        sidePanel.add(sidePanelBgImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, -1));

        bgPanel.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        loginPanel.setBackground(new java.awt.Color(51, 51, 51));
        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contacts-xxl.png"))); // NOI18N
        loginPanel.add(userIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 130, -1));

        passPanel.setBackground(new java.awt.Color(153, 153, 153));
        passPanel.setOpaque(false);
        passPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        smallKeyIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smallKey.png"))); // NOI18N
        passPanel.add(smallKeyIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        passPaneSeparator.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        passPaneSeparator.setForeground(new java.awt.Color(255, 255, 255));
        passPaneSeparator.setText("|");
        passPanel.add(passPaneSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 30, 30));
        passPanel.add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 180, 30));

        loginPanel.add(passPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 260, 50));

        emailPanel.setBackground(new java.awt.Color(153, 153, 153));
        emailPanel.setOpaque(false);
        emailPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        smallUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniUserIcon.png"))); // NOI18N
        emailPanel.add(smallUserIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        emailPaneSeparator.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        emailPaneSeparator.setForeground(new java.awt.Color(255, 255, 255));
        emailPaneSeparator.setText("|");
        emailPanel.add(emailPaneSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 30, 30));

        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        emailPanel.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 180, 30));

        loginPanel.add(emailPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 260, 50));

        passLabel.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        passLabel.setForeground(new java.awt.Color(255, 255, 255));
        passLabel.setText("Pass");
        loginPanel.add(passLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        emailLabel.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel.setText("Email");
        loginPanel.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        loginButton.setBackground(new java.awt.Color(38, 55, 120));
        loginButton.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login");
        loginButton.setBorder(null);
        loginButton.setBorderPainted(false);
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginPanel.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 140, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ballpen.png"))); // NOI18N
        loginPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 110, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search.png"))); // NOI18N
        loginPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 110, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Document.png"))); // NOI18N
        loginPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 380, 100, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OpenBook.png"))); // NOI18N
        loginPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, 90, -1));

        jLabel5.setForeground(new java.awt.Color(0, 153, 0));
        jLabel5.setText("here");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        loginPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Or sign up");
        loginPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, -1, -1));

        bgPanel.add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 360, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_loginButtonActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        System.out.println("Hello world");
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanel;
    private javax.swing.JLabel ccstLogo;
    private javax.swing.JLabel eduSyncSlogan;
    private javax.swing.JLabel eduSyncTitle;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailPaneSeparator;
    private javax.swing.JPanel emailPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField passField;
    private javax.swing.JLabel passLabel;
    private javax.swing.JLabel passPaneSeparator;
    private javax.swing.JPanel passPanel;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JLabel sidePanelBgImage;
    private javax.swing.JLabel smallKeyIcon;
    private javax.swing.JLabel smallUserIcon;
    private javax.swing.JLabel userIcon;
    // End of variables declaration//GEN-END:variables
    class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
    }

}
