/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.interfacetest;

import java.awt.Font;
import java.io.File;

/**
 *
 * @author avery
 */
public class Mainpage extends javax.swing.JFrame {

    /**
     * Creates new form Mainpage
     */
    public Mainpage() {
        initComponents();
        try {
            File importTitleFont = new File("src/main/resources/Fonts/Anton-Regular.ttf");
            File importBodyFont = new File("src/main/resources/Fonts/MajorMonoDisplay-Regular.ttf");
            File importAccentFont = new File("src/main/resources/Fonts/OpenSans-Regular.ttf");
            
            // Assign fonts to variables, set font size
            Font titleFont = Font.createFont(Font.TRUETYPE_FONT, importTitleFont);
            Font bodyFont = Font.createFont(Font.TRUETYPE_FONT, importBodyFont);
            Font accentFont = Font.createFont(Font.TRUETYPE_FONT, importAccentFont);
            
            // Set font for UI **BELOW**
            homeSidePanelText.setFont(accentFont.deriveFont(16f));
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        mainPageSidePanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        mainpageHomeIcon = new javax.swing.JLabel();
        homeSidePanelText = new javax.swing.JLabel();
        mainPageNavbar = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundPanel.setForeground(new java.awt.Color(60, 63, 65));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPageSidePanel.setBackground(new java.awt.Color(51, 51, 51));
        mainPageSidePanel.setForeground(new java.awt.Color(51, 51, 51));
        mainPageSidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        mainPageSidePanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 220, 20));

        mainpageHomeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPageIcons/HomeMiniIcon.png"))); // NOI18N
        mainPageSidePanel.add(mainpageHomeIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 30, -1));

        homeSidePanelText.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        homeSidePanelText.setText("Home");
        mainPageSidePanel.add(homeSidePanelText, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 40));

        backgroundPanel.add(mainPageSidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 240, 600));

        mainPageNavbar.setBackground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout mainPageNavbarLayout = new javax.swing.GroupLayout(mainPageNavbar);
        mainPageNavbar.setLayout(mainPageNavbarLayout);
        mainPageNavbarLayout.setHorizontalGroup(
            mainPageNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
        );
        mainPageNavbarLayout.setVerticalGroup(
            mainPageNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        backgroundPanel.add(mainPageNavbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel homeSidePanelText;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel mainPageNavbar;
    private javax.swing.JPanel mainPageSidePanel;
    private javax.swing.JLabel mainpageHomeIcon;
    // End of variables declaration//GEN-END:variables
}
