/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.interfacetest;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author avery
 */
public class newMainPage extends javax.swing.JFrame {
    // import homepage side panel icons
    // - Selected Icons
    ImageIcon homeSelectedIcon = new ImageIcon("src/main/resources/mainPageIcons/whiteHome.png");
    ImageIcon dashboardSelectedIcon = new ImageIcon("src/main/resources/mainPageIcons/whiteLaptop.png");
    ImageIcon studentSelectedIcon = new ImageIcon("src/main/resources/mainPageIcons/whiteStudent.png");
    ImageIcon sectionsSelectedIcon = new ImageIcon("src/main/resources/mainPageIcons/whiteSections.png");
    ImageIcon attendanceSelectedIcon = new ImageIcon("src/main/resources/mainPageIcons/whiteAttendance.png");
    
    // - Unselected Icons
    ImageIcon homeUnselectedIcon = new ImageIcon("src/main/resources/mainPageIcons/unselectedHome.png");
    ImageIcon dashboardUnselectedIcon = new ImageIcon("src/main/resources/mainPageIcons/unselectedDashboard.png");
    ImageIcon studentUnselectedIcon = new ImageIcon("src/main/resources/mainPageIcons/unselectedStudent.png");
    ImageIcon sectionsUnselectedIcon = new ImageIcon("src/main/resources/mainPageIcons/unselectedSections.png");
    ImageIcon attendanceUnselectedIcon = new ImageIcon("src/main/resources/mainPageIcons/unselectedAttendance.png");
    /**
     * Creates new form newMainPage
     */
    public newMainPage() {
        initComponents();
            try {
                UIManager.setLookAndFeel(new FlatLightLaf());
                SwingUtilities.updateComponentTreeUI(this);
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(FlatLaftest.class.getName()).log(Level.SEVERE, null, ex);
            }
        try {
            File importTitleFont = new File("src/main/resources/Fonts/Anton-Regular.ttf");
            File importBodyFont = new File("src/main/resources/Fonts/MajorMonoDisplay-Regular.ttf");
            File importAccentFont = new File("src/main/resources/Fonts/OpenSans-Regular.ttf");
            File importLightNumFont = new File("src/main/resources/Fonts/Lato-Light.ttf");
            File importNumFont = new File("src/main/resources/Fonts/Lato-Black.ttf");
            
            // Assign fonts to variables, set font size
            Font titleFont = Font.createFont(Font.TRUETYPE_FONT, importTitleFont);
            Font bodyFont = Font.createFont(Font.TRUETYPE_FONT, importBodyFont);
            Font accentFont = Font.createFont(Font.TRUETYPE_FONT, importAccentFont);
            Font lightNumFont = Font.createFont(Font.TRUETYPE_FONT, importLightNumFont);
            Font numFont = Font.createFont(Font.TRUETYPE_FONT, importNumFont);
            
            // Set Fonts
            homePageWelcomeLabel.setFont(titleFont.deriveFont(36f));
            
            mainPageDesc1.setFont(accentFont.deriveFont(14f));
            mainPageDesc2.setFont(accentFont.deriveFont(14f));
            mainPageDesc3.setFont(accentFont.deriveFont(14f));
            
            dashboardGreetingsLabel.setFont(accentFont.deriveFont(24f));
            dashboardUsernameLabel.setFont(titleFont.deriveFont(36f));
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        background = new javax.swing.JPanel();
        sidePanel = new RoundedPanel(15, new Color(70,131,166, 220));
        edusyncSidePanelTitle = new javax.swing.JLabel();
        sidePanelAttendanceButton = new javax.swing.JPanel();
        sidePanelAttendanceText = new javax.swing.JLabel();
        miniAttendanceIcon = new javax.swing.JLabel();
        attendanceSelector = new javax.swing.JLabel();
        sidePanelHomeButton = new javax.swing.JPanel();
        sidePanelHomeText = new javax.swing.JLabel();
        miniHomeIcon = new javax.swing.JLabel();
        homeSelector = new javax.swing.JLabel();
        sidePanelDashButton1 = new javax.swing.JPanel();
        sidePanelDashText1 = new javax.swing.JLabel();
        miniDashboardIcon = new javax.swing.JLabel();
        dashboardSelector = new javax.swing.JLabel();
        sidePanelStudentButton1 = new javax.swing.JPanel();
        sidePanelStudentText1 = new javax.swing.JLabel();
        miniStudentIcon = new javax.swing.JLabel();
        studentSelector = new javax.swing.JLabel();
        sidePanelSectionsButton1 = new javax.swing.JPanel();
        sidePanelSectionsText1 = new javax.swing.JLabel();
        miniSectionsIcon = new javax.swing.JLabel();
        sectionsSelector = new javax.swing.JLabel();
        mainPagePanels = new javax.swing.JTabbedPane();
        homeBackgroundPanel = new javax.swing.JPanel();
        homeMainPanel = new RoundedPanel(15, new Color(70,131,166, 220));
        homeSearchPanel = new RoundedPanel(30, new Color(255, 255, 255));
        homePageSearchButton = new javax.swing.JLabel();
        homePageSearchField = new javax.swing.JTextField();
        homePageWelcomeLabel = new javax.swing.JLabel();
        mainPageDesc3 = new javax.swing.JLabel();
        mainPageDesc1 = new javax.swing.JLabel();
        mainPageDesc2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dashboardBackgroundPanel = new javax.swing.JPanel();
        dashboardMainPanel = new RoundedPanel(15, new Color(70,131,166, 220));
        dashboardUsernameLabel = new javax.swing.JLabel();
        dashboardGreetingsLabel = new javax.swing.JLabel();
        dashboardStudentCountPanel1 = new javax.swing.JPanel();
        dashboardAttendanceLabel = new javax.swing.JLabel();
        dashboardAttendancePercentage = new javax.swing.JLabel();
        dashboardAttendanceIcon = new javax.swing.JLabel();
        dashboardStudentCountPanel = new javax.swing.JPanel();
        dashboardStudentCountNum = new javax.swing.JLabel();
        dashboardStudentCountLabel = new javax.swing.JLabel();
        dashboardStudentCountIcon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        gaugeChart1 = new CustomizedElements.GaugeChart();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        dashboardBestInAttendanceIcon1 = new javax.swing.JLabel();
        dashboardBestInAttendanceSection = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        dashboardBestInMarksIcon = new javax.swing.JLabel();
        dashboardBestInMarksSection = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        dashboardMostImprovedAttendanceIcon = new javax.swing.JLabel();
        dashboardMostImprovedAttendanceSection = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        dashboardMostImprovedMarks = new javax.swing.JLabel();
        dashboardMostImprovedSection = new javax.swing.JLabel();
        dashboardBestInAttendanceLabel = new javax.swing.JLabel();
        dashboardBestInMarksLabel = new javax.swing.JLabel();
        dashboardMostImprovedMarksLabel = new javax.swing.JLabel();
        dashboardMostImprovedAttendasnceLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        gaugeChart2 = new CustomizedElements.GaugeChart();
        jLabel1 = new javax.swing.JLabel();

        jLabel7.setFont(new java.awt.Font("Open Sans", 0, 10)); // NOI18N
        jLabel7.setText("ICT 12D");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EduSync");
        setResizable(false);

        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(70, 131, 166));
        sidePanel.setOpaque(false);
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        edusyncSidePanelTitle.setFont(new java.awt.Font("Anton", 0, 48)); // NOI18N
        edusyncSidePanelTitle.setForeground(new java.awt.Color(255, 255, 255));
        edusyncSidePanelTitle.setText("EduSync");
        sidePanel.add(edusyncSidePanelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        sidePanelAttendanceButton.setForeground(new java.awt.Color(255, 255, 255));
        sidePanelAttendanceButton.setOpaque(false);
        sidePanelAttendanceButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sidePanelAttendanceButtonMouseClicked(evt);
            }
        });
        sidePanelAttendanceButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanelAttendanceText.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        sidePanelAttendanceText.setForeground(new java.awt.Color(255, 255, 255));
        sidePanelAttendanceText.setText("Attendance");
        sidePanelAttendanceButton.add(sidePanelAttendanceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        miniAttendanceIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPageIcons/unselectedAttendance.png"))); // NOI18N
        miniAttendanceIcon.setText("jLabel6");
        sidePanelAttendanceButton.add(miniAttendanceIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, -1));

        attendanceSelector.setFont(new java.awt.Font("Dialog", 0, 60)); // NOI18N
        attendanceSelector.setForeground(new java.awt.Color(0, 153, 153));
        sidePanelAttendanceButton.add(attendanceSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, 90));

        sidePanel.add(sidePanelAttendanceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 260, 60));

        sidePanelHomeButton.setBackground(new java.awt.Color(70,131,166, 220));
        sidePanelHomeButton.setToolTipText("");
        sidePanelHomeButton.setOpaque(false);
        sidePanelHomeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sidePanelHomeButtonMouseClicked(evt);
            }
        });
        sidePanelHomeButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanelHomeText.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        sidePanelHomeText.setForeground(new java.awt.Color(255, 255, 255));
        sidePanelHomeText.setText("Home");
        sidePanelHomeButton.add(sidePanelHomeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, 30));

        miniHomeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPageIcons/unselectedHome.png"))); // NOI18N
        miniHomeIcon.setText("jLabel3");
        sidePanelHomeButton.add(miniHomeIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, -1));

        homeSelector.setFont(new java.awt.Font("Dialog", 0, 60)); // NOI18N
        homeSelector.setForeground(new java.awt.Color(0, 153, 153));
        sidePanelHomeButton.add(homeSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, 90));

        sidePanel.add(sidePanelHomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 260, 60));

        sidePanelDashButton1.setOpaque(false);
        sidePanelDashButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sidePanelDashButton1MouseClicked(evt);
            }
        });
        sidePanelDashButton1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanelDashText1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        sidePanelDashText1.setForeground(new java.awt.Color(255, 255, 255));
        sidePanelDashText1.setText("Dashboard");
        sidePanelDashButton1.add(sidePanelDashText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        miniDashboardIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPageIcons/unselectedDashboard.png"))); // NOI18N
        miniDashboardIcon.setText("jLabel4");
        sidePanelDashButton1.add(miniDashboardIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, -1));

        dashboardSelector.setFont(new java.awt.Font("Dialog", 0, 60)); // NOI18N
        dashboardSelector.setForeground(new java.awt.Color(0, 153, 153));
        sidePanelDashButton1.add(dashboardSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, 90));

        sidePanel.add(sidePanelDashButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 260, 60));

        sidePanelStudentButton1.setOpaque(false);
        sidePanelStudentButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sidePanelStudentButton1MouseClicked(evt);
            }
        });
        sidePanelStudentButton1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanelStudentText1.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        sidePanelStudentText1.setForeground(new java.awt.Color(255, 255, 255));
        sidePanelStudentText1.setText("Students");
        sidePanelStudentButton1.add(sidePanelStudentText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        miniStudentIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPageIcons/unselectedStudent.png"))); // NOI18N
        miniStudentIcon.setText("jLabel2");
        sidePanelStudentButton1.add(miniStudentIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, -1));

        studentSelector.setFont(new java.awt.Font("Dialog", 0, 60)); // NOI18N
        studentSelector.setForeground(new java.awt.Color(0, 153, 153));
        sidePanelStudentButton1.add(studentSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, 90));

        sidePanel.add(sidePanelStudentButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 260, 60));

        sidePanelSectionsButton1.setOpaque(false);
        sidePanelSectionsButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sidePanelSectionsButton1MouseClicked(evt);
            }
        });
        sidePanelSectionsButton1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanelSectionsText1.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        sidePanelSectionsText1.setForeground(new java.awt.Color(255, 255, 255));
        sidePanelSectionsText1.setText("Sections");
        sidePanelSectionsButton1.add(sidePanelSectionsText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        miniSectionsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPageIcons/unselectedSections.png"))); // NOI18N
        miniSectionsIcon.setText("jLabel5");
        sidePanelSectionsButton1.add(miniSectionsIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, -1));

        sectionsSelector.setFont(new java.awt.Font("Dialog", 0, 60)); // NOI18N
        sectionsSelector.setForeground(new java.awt.Color(0, 153, 153));
        sidePanelSectionsButton1.add(sectionsSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, 90));

        sidePanel.add(sidePanelSectionsButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 260, 60));

        background.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 260, 620));

        homeBackgroundPanel.setOpaque(false);
        homeBackgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeMainPanel.setBackground(new java.awt.Color(70, 131, 166));
        homeMainPanel.setOpaque(false);
        homeMainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeSearchPanel.setBackground(new java.awt.Color(255, 255, 255));
        homeSearchPanel.setOpaque(false);
        homeSearchPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homePageSearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPageIcons/newSearch.png"))); // NOI18N
        homeSearchPanel.add(homePageSearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 40, 40));

        homePageSearchField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        homePageSearchField.setForeground(new java.awt.Color(70, 131, 166));
        homePageSearchField.setBorder(null);
        homeSearchPanel.add(homePageSearchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 320, 40));

        homeMainPanel.add(homeSearchPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 390, 40));

        homePageWelcomeLabel.setFont(new java.awt.Font("Anton", 0, 36)); // NOI18N
        homePageWelcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        homePageWelcomeLabel.setText("Welcome to EduSync!");
        homeMainPanel.add(homePageWelcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        mainPageDesc3.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        mainPageDesc3.setForeground(new java.awt.Color(255, 255, 255));
        mainPageDesc3.setText("tasks and improve academic experiences.");
        homeMainPanel.add(mainPageDesc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, 290, 20));

        mainPageDesc1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        mainPageDesc1.setForeground(new java.awt.Color(255, 255, 255));
        mainPageDesc1.setText("Empowering educational institutions with efficiency and simplicity. Our Student ");
        homeMainPanel.add(mainPageDesc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, -1, 20));

        mainPageDesc2.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        mainPageDesc2.setForeground(new java.awt.Color(255, 255, 255));
        mainPageDesc2.setText("Management System provides a compehensive solution to streamline administrative");
        homeMainPanel.add(mainPageDesc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, -1, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPageIcons/EduSync-Logo.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        homeMainPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 230, -1));

        jLabel3.setText("jLabel3");
        homeMainPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 210, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPageIcons/Close.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        homeMainPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 50, -1));

        homeBackgroundPanel.add(homeMainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 800, 630));

        mainPagePanels.addTab("ddd", homeBackgroundPanel);

        dashboardBackgroundPanel.setOpaque(false);
        dashboardBackgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboardMainPanel.setBackground(new java.awt.Color(70, 131, 166));
        dashboardMainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboardUsernameLabel.setFont(new java.awt.Font("Anton", 0, 36)); // NOI18N
        dashboardUsernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        dashboardUsernameLabel.setText("[user]");
        dashboardMainPanel.add(dashboardUsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        dashboardGreetingsLabel.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        dashboardGreetingsLabel.setForeground(new java.awt.Color(255, 255, 255));
        dashboardGreetingsLabel.setText("Good Day,");
        dashboardMainPanel.add(dashboardGreetingsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        dashboardStudentCountPanel1.setBackground(new java.awt.Color(255, 255, 255));
        dashboardStudentCountPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        dashboardStudentCountPanel1.setForeground(new java.awt.Color(255, 255, 255));
        dashboardStudentCountPanel1.setOpaque(false);
        dashboardStudentCountPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboardAttendanceLabel.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        dashboardAttendanceLabel.setForeground(new java.awt.Color(255, 255, 255));
        dashboardAttendanceLabel.setText("Attendance");
        dashboardStudentCountPanel1.add(dashboardAttendanceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        dashboardAttendancePercentage.setFont(new java.awt.Font("Lato Light", 0, 30)); // NOI18N
        dashboardAttendancePercentage.setForeground(new java.awt.Color(255, 255, 255));
        dashboardAttendancePercentage.setText("87.55%");
        dashboardStudentCountPanel1.add(dashboardAttendancePercentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 110, 40));

        dashboardAttendanceIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPageIcons/dashboardAttendance.png"))); // NOI18N
        dashboardAttendanceIcon.setText("jLabel8");
        dashboardStudentCountPanel1.add(dashboardAttendanceIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, -1));

        dashboardMainPanel.add(dashboardStudentCountPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 210, 80));

        dashboardStudentCountPanel.setBackground(new java.awt.Color(255, 255, 255));
        dashboardStudentCountPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        dashboardStudentCountPanel.setForeground(new java.awt.Color(255, 255, 255));
        dashboardStudentCountPanel.setOpaque(false);
        dashboardStudentCountPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboardStudentCountNum.setFont(new java.awt.Font("Lato Light", 0, 36)); // NOI18N
        dashboardStudentCountNum.setForeground(new java.awt.Color(255, 255, 255));
        dashboardStudentCountNum.setText("5,000");
        dashboardStudentCountPanel.add(dashboardStudentCountNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 100, 40));

        dashboardStudentCountLabel.setFont(new java.awt.Font("Open Sans", 2, 13)); // NOI18N
        dashboardStudentCountLabel.setForeground(new java.awt.Color(255, 255, 255));
        dashboardStudentCountLabel.setText("Student Count");
        dashboardStudentCountPanel.add(dashboardStudentCountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 90, 20));

        dashboardStudentCountIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPageIcons/StudentCount.png"))); // NOI18N
        dashboardStudentCountIcon.setText("jLabel6");
        dashboardStudentCountPanel.add(dashboardStudentCountIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, -1));

        dashboardMainPanel.add(dashboardStudentCountPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 210, 80));

        gaugeChart1.setBackground(new java.awt.Color(255, 51, 51));
        gaugeChart1.setValue(60);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(gaugeChart1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(gaugeChart1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        dashboardMainPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 430, 290));

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(102, 204, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("John Doe");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jLabel17.setFont(new java.awt.Font("Lato Light", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("87.5%");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        dashboardBestInAttendanceIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPageIcons/boystudent.png"))); // NOI18N
        dashboardBestInAttendanceIcon1.setText("jLabel13");
        jPanel5.add(dashboardBestInAttendanceIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 60, -1));

        dashboardBestInAttendanceSection.setFont(new java.awt.Font("Open Sans", 0, 10)); // NOI18N
        dashboardBestInAttendanceSection.setText("ICT 12D");
        jPanel5.add(dashboardBestInAttendanceSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 80));

        jPanel6.setBackground(new java.awt.Color(102, 204, 255));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel6.setOpaque(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Sarah Collins");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jLabel18.setFont(new java.awt.Font("Lato Light", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("97.5%");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        dashboardBestInMarksIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPageIcons/student.png"))); // NOI18N
        dashboardBestInMarksIcon.setText("jLabel5");
        jPanel6.add(dashboardBestInMarksIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 60, -1));

        dashboardBestInMarksSection.setFont(new java.awt.Font("Open Sans", 0, 10)); // NOI18N
        dashboardBestInMarksSection.setText("ICT 12D");
        jPanel6.add(dashboardBestInMarksSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 150, 80));

        jPanel7.setBackground(new java.awt.Color(102, 204, 255));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel7.setOpaque(false);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Chris Lee");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 90, -1));

        jLabel19.setFont(new java.awt.Font("Lato Light", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("89.8%");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        dashboardMostImprovedAttendanceIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPageIcons/boystudent.png"))); // NOI18N
        dashboardMostImprovedAttendanceIcon.setText("jLabel13");
        jPanel7.add(dashboardMostImprovedAttendanceIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 60, -1));

        dashboardMostImprovedAttendanceSection.setFont(new java.awt.Font("Open Sans", 0, 10)); // NOI18N
        dashboardMostImprovedAttendanceSection.setText("ICT 12D");
        jPanel7.add(dashboardMostImprovedAttendanceSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 160, 80));

        jPanel8.setBackground(new java.awt.Color(102, 204, 255));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel8.setOpaque(false);
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Erina Smith");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jLabel14.setFont(new java.awt.Font("Lato Light", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("94.3%");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        dashboardMostImprovedMarks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPageIcons/student.png"))); // NOI18N
        dashboardMostImprovedMarks.setText("jLabel5");
        jPanel8.add(dashboardMostImprovedMarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 60, -1));

        dashboardMostImprovedSection.setFont(new java.awt.Font("Open Sans", 0, 10)); // NOI18N
        dashboardMostImprovedSection.setText("ICT 12D");
        jPanel8.add(dashboardMostImprovedSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 150, 80));

        dashboardBestInAttendanceLabel.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        dashboardBestInAttendanceLabel.setForeground(new java.awt.Color(255, 255, 255));
        dashboardBestInAttendanceLabel.setText("Best in Attendance");
        jPanel3.add(dashboardBestInAttendanceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        dashboardBestInMarksLabel.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        dashboardBestInMarksLabel.setForeground(new java.awt.Color(255, 255, 255));
        dashboardBestInMarksLabel.setText("Best in Marks");
        jPanel3.add(dashboardBestInMarksLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        dashboardMostImprovedMarksLabel.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        dashboardMostImprovedMarksLabel.setForeground(new java.awt.Color(255, 255, 255));
        dashboardMostImprovedMarksLabel.setText("Most Improved in Marks");
        jPanel3.add(dashboardMostImprovedMarksLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 160, -1));

        dashboardMostImprovedAttendasnceLabel.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        dashboardMostImprovedAttendasnceLabel.setForeground(new java.awt.Color(255, 255, 255));
        dashboardMostImprovedAttendasnceLabel.setText("Most Improved in Attendance");
        jPanel3.add(dashboardMostImprovedAttendasnceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 160, -1));

        dashboardMainPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 340, 230));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );

        dashboardMainPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 340, 220));

        gaugeChart2.setColor1(new java.awt.Color(153, 153, 0));
        gaugeChart2.setValue(90);
        dashboardMainPanel.add(gaugeChart2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        dashboardBackgroundPanel.add(dashboardMainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 800, 630));

        mainPagePanels.addTab("tab2", dashboardBackgroundPanel);

        background.add(mainPagePanels, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, -30, 840, 710));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPageIcons/mainpageBGIMAGE.png"))); // NOI18N
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sidePanelHomeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidePanelHomeButtonMouseClicked
        //Handling other selectors
        studentSelector.setText("");
        dashboardSelector.setText("");
        sectionsSelector.setText("");
        attendanceSelector.setText("");
        
        // sets selector for home button
        homeSelector.setText("|");
        homeSelector.setForeground(new Color(255,255,255));
        
        // reset unselected button for other labels
        miniDashboardIcon.setIcon(dashboardUnselectedIcon);
        miniStudentIcon.setIcon(studentUnselectedIcon);
        miniSectionsIcon.setIcon(sectionsUnselectedIcon);
        miniAttendanceIcon.setIcon(attendanceUnselectedIcon);
        
        // set icon for selected home button
        miniHomeIcon.setIcon(homeSelectedIcon);
        
        // set index for tabbed pane
        mainPagePanels.setSelectedIndex(0);
    }//GEN-LAST:event_sidePanelHomeButtonMouseClicked

    private void sidePanelDashButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidePanelDashButton1MouseClicked
        //Handling other selectors
        homeSelector.setText("");
        studentSelector.setText("");
        sectionsSelector.setText("");
        attendanceSelector.setText("");
        
        // set selector for dashboard button
        dashboardSelector.setText("|");
        dashboardSelector.setForeground(new Color(255,255,255));
        
        // reset unselected button for other labels
        miniHomeIcon.setIcon(homeUnselectedIcon);
        miniStudentIcon.setIcon(studentUnselectedIcon);
        miniSectionsIcon.setIcon(sectionsUnselectedIcon);
        miniAttendanceIcon.setIcon(attendanceUnselectedIcon);
        
        // set icon for selected dashboard
        miniDashboardIcon.setIcon(dashboardSelectedIcon);
        
        // set index for tabbed pane
        mainPagePanels.setSelectedIndex(1);
    }//GEN-LAST:event_sidePanelDashButton1MouseClicked

    private void sidePanelStudentButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidePanelStudentButton1MouseClicked
        homeSelector.setText("");
        sectionsSelector.setText("");
        dashboardSelector.setText("");
        attendanceSelector.setText("");
        
        studentSelector.setText("|");
        studentSelector.setForeground(new Color(255,255,255));
        
        // reset unselected button for other labels
        miniHomeIcon.setIcon(homeUnselectedIcon);
        miniDashboardIcon.setIcon(dashboardUnselectedIcon);
        miniSectionsIcon.setIcon(sectionsUnselectedIcon);
        miniAttendanceIcon.setIcon(attendanceUnselectedIcon);
        
        
        // set icon for selected student
        miniStudentIcon.setIcon(studentSelectedIcon);
    }//GEN-LAST:event_sidePanelStudentButton1MouseClicked

    private void sidePanelSectionsButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidePanelSectionsButton1MouseClicked
        //Handling other selectors
        homeSelector.setText("");
        studentSelector.setText("");
        dashboardSelector.setText("");
        attendanceSelector.setText("");
        
        sectionsSelector.setText("|");
        sectionsSelector.setForeground(new Color(255,255,255));
        
        // reset unselected button for other labels
        miniHomeIcon.setIcon(homeUnselectedIcon);
        miniDashboardIcon.setIcon(dashboardUnselectedIcon);
        miniStudentIcon.setIcon(studentUnselectedIcon);
        miniAttendanceIcon.setIcon(attendanceUnselectedIcon);
        
        // set icon for selected sections
        miniSectionsIcon.setIcon(sectionsSelectedIcon);
    }//GEN-LAST:event_sidePanelSectionsButton1MouseClicked

    private void sidePanelAttendanceButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidePanelAttendanceButtonMouseClicked
       //Handling other selectors
       homeSelector.setText("");
        studentSelector.setText("");
        dashboardSelector.setText("");
        sectionsSelector.setText("");
        
        attendanceSelector.setText("|");
        attendanceSelector.setForeground(new Color(255,255,255));
        
        // reset unselected button for other labels
        miniHomeIcon.setIcon(homeUnselectedIcon);
        miniDashboardIcon.setIcon(dashboardUnselectedIcon);
        miniStudentIcon.setIcon(sectionsUnselectedIcon);
        miniSectionsIcon.setIcon(attendanceUnselectedIcon);
        
        // set icon for selected attendance
        miniAttendanceIcon.setIcon(attendanceSelectedIcon);
    }//GEN-LAST:event_sidePanelAttendanceButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newMainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel attendanceSelector;
    private javax.swing.JPanel background;
    private javax.swing.JLabel dashboardAttendanceIcon;
    private javax.swing.JLabel dashboardAttendanceLabel;
    private javax.swing.JLabel dashboardAttendancePercentage;
    private javax.swing.JPanel dashboardBackgroundPanel;
    private javax.swing.JLabel dashboardBestInAttendanceIcon1;
    private javax.swing.JLabel dashboardBestInAttendanceLabel;
    private javax.swing.JLabel dashboardBestInAttendanceSection;
    private javax.swing.JLabel dashboardBestInMarksIcon;
    private javax.swing.JLabel dashboardBestInMarksLabel;
    private javax.swing.JLabel dashboardBestInMarksSection;
    private javax.swing.JLabel dashboardGreetingsLabel;
    private javax.swing.JPanel dashboardMainPanel;
    private javax.swing.JLabel dashboardMostImprovedAttendanceIcon;
    private javax.swing.JLabel dashboardMostImprovedAttendanceSection;
    private javax.swing.JLabel dashboardMostImprovedAttendasnceLabel;
    private javax.swing.JLabel dashboardMostImprovedMarks;
    private javax.swing.JLabel dashboardMostImprovedMarksLabel;
    private javax.swing.JLabel dashboardMostImprovedSection;
    private javax.swing.JLabel dashboardSelector;
    private javax.swing.JLabel dashboardStudentCountIcon;
    private javax.swing.JLabel dashboardStudentCountLabel;
    private javax.swing.JLabel dashboardStudentCountNum;
    private javax.swing.JPanel dashboardStudentCountPanel;
    private javax.swing.JPanel dashboardStudentCountPanel1;
    public javax.swing.JLabel dashboardUsernameLabel;
    private javax.swing.JLabel edusyncSidePanelTitle;
    private CustomizedElements.GaugeChart gaugeChart1;
    private CustomizedElements.GaugeChart gaugeChart2;
    private javax.swing.JPanel homeBackgroundPanel;
    private javax.swing.JPanel homeMainPanel;
    private javax.swing.JLabel homePageSearchButton;
    private javax.swing.JTextField homePageSearchField;
    private javax.swing.JLabel homePageWelcomeLabel;
    private javax.swing.JPanel homeSearchPanel;
    private javax.swing.JLabel homeSelector;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel mainPageDesc1;
    private javax.swing.JLabel mainPageDesc2;
    private javax.swing.JLabel mainPageDesc3;
    private javax.swing.JTabbedPane mainPagePanels;
    private javax.swing.JLabel miniAttendanceIcon;
    private javax.swing.JLabel miniDashboardIcon;
    private javax.swing.JLabel miniHomeIcon;
    private javax.swing.JLabel miniSectionsIcon;
    private javax.swing.JLabel miniStudentIcon;
    private javax.swing.JLabel sectionsSelector;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel sidePanelAttendanceButton;
    private javax.swing.JLabel sidePanelAttendanceText;
    private javax.swing.JPanel sidePanelDashButton1;
    private javax.swing.JLabel sidePanelDashText1;
    private javax.swing.JPanel sidePanelHomeButton;
    private javax.swing.JLabel sidePanelHomeText;
    private javax.swing.JPanel sidePanelSectionsButton1;
    private javax.swing.JLabel sidePanelSectionsText1;
    private javax.swing.JPanel sidePanelStudentButton1;
    private javax.swing.JLabel sidePanelStudentText1;
    private javax.swing.JLabel studentSelector;
    // End of variables declaration//GEN-END:variables
    class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        @Override
        protected void paintComponent(Graphics g) {
super.paintComponent(g);
        Graphics2D graphics = (Graphics2D) g.create(); // Create a copy of the graphics object
        Dimension arcs = new Dimension(cornerRadius, cornerRadius);
        int width = getWidth();
        int height = getHeight();

        graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        if (backgroundColor != null) {
            graphics.setColor(backgroundColor);
        } else {
            graphics.setColor(getBackground());
        }
        graphics.fillRoundRect(0, 0, width - 1, height - 1, arcs.width, arcs.height); // Paint background
        graphics.setColor(getForeground());
        // graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); // Paint border

        graphics.dispose(); // Dispose of the graphics object
//           
            }
        }
        
}
