/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.interfacetest;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.io.File;
import javax.swing.JPanel;

/**
 *
 * @author avery
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        try {
            // Import fonts
            File importTitleFont = new File("src/main/resources/Fonts/Anton-Regular.ttf");
            File importBodyFont = new File("src/main/resources/Fonts/MajorMonoDisplay-Regular.ttf");
            File importAccentFont = new File("src/main/resources/Fonts/OpenSans-Regular.ttf");
            
            // Assign fonts to variables, set font size
            Font titleFont = Font.createFont(Font.TRUETYPE_FONT, importTitleFont).deriveFont(60f);
            Font bodyFont = Font.createFont(Font.TRUETYPE_FONT, importBodyFont).deriveFont(18f);
            Font accentFont = Font.createFont(Font.TRUETYPE_FONT, importAccentFont).deriveFont(14f);
            
            // Set font for UI **BELOW**
            signUpTitle.setFont(titleFont);
            
            confirmSignupButton.setFont(Font.createFont(Font.TRUETYPE_FONT, importAccentFont).deriveFont(18f));
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        signUpPanel = new javax.swing.JPanel();
        signUpEmailPanel = new RoundedPanel(15,new Color(60,63,65));
        emailMiniIcon = new javax.swing.JLabel();
        emailEntryField = new javax.swing.JTextField();
        signUpPasswordPanel = new RoundedPanel(15,new Color(60,63,65));
        passwordIcon = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        confirmPasswordPanel = new RoundedPanel(15,new Color(60,63,65));
        confirmPasswordIcon = new javax.swing.JLabel();
        confirmPasswordField = new javax.swing.JPasswordField();
        confirmSignupButton = new javax.swing.JButton();
        signUpTitle = new javax.swing.JLabel();
        signUpBg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EDUSYNC - SIGN UP");
        setResizable(false);

        backgroundPanel.setBackground(new java.awt.Color(51, 51, 51));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signUpPanel.setForeground(new java.awt.Color(60, 63, 65));
        signUpPanel.setOpaque(false);
        signUpPanel.setPreferredSize(new java.awt.Dimension(368, 506));
        signUpPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signUpEmailPanel.setForeground(new java.awt.Color(60, 63, 65));
        signUpEmailPanel.setOpaque(false);
        signUpEmailPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailMiniIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signupIcons/mailMiniIcon.png"))); // NOI18N
        signUpEmailPanel.add(emailMiniIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        emailEntryField.setForeground(new java.awt.Color(38, 55, 120));
        signUpEmailPanel.add(emailEntryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 210, 30));

        signUpPanel.add(signUpEmailPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 290, 50));

        signUpPasswordPanel.setOpaque(false);
        signUpPasswordPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passwordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signupIcons/passMiniIcon.png"))); // NOI18N
        signUpPasswordPanel.add(passwordIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        passwordField.setForeground(new java.awt.Color(38, 55, 120));
        signUpPasswordPanel.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 210, 30));

        signUpPanel.add(signUpPasswordPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 290, 50));

        confirmPasswordPanel.setOpaque(false);
        confirmPasswordPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        confirmPasswordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signupIcons/passMiniIcon.png"))); // NOI18N
        confirmPasswordPanel.add(confirmPasswordIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        confirmPasswordField.setForeground(new java.awt.Color(38, 55, 120));
        confirmPasswordPanel.add(confirmPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 210, 30));

        signUpPanel.add(confirmPasswordPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 290, 50));

        confirmSignupButton.setBackground(new java.awt.Color(38, 55, 120));
        confirmSignupButton.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        confirmSignupButton.setForeground(new java.awt.Color(255, 255, 255));
        confirmSignupButton.setText("Confirm");
        confirmSignupButton.setBorderPainted(false);
        confirmSignupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmSignupButtonActionPerformed(evt);
            }
        });
        signUpPanel.add(confirmSignupButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 110, 50));

        signUpTitle.setFont(new java.awt.Font("Anton", 0, 60)); // NOI18N
        signUpTitle.setForeground(new java.awt.Color(255, 255, 255));
        signUpTitle.setText("SIGN UP");
        signUpPanel.add(signUpTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        signUpBg.setForeground(new java.awt.Color(60, 63, 65));
        signUpBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signupIcons/singupPanelBg.png"))); // NOI18N
        signUpPanel.add(signUpBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        backgroundPanel.add(signUpPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signupIcons/bgImage.png"))); // NOI18N
        backgroundPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmSignupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmSignupButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmSignupButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JLabel confirmPasswordIcon;
    private javax.swing.JPanel confirmPasswordPanel;
    private javax.swing.JButton confirmSignupButton;
    private javax.swing.JTextField emailEntryField;
    private javax.swing.JLabel emailMiniIcon;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordIcon;
    private javax.swing.JLabel signUpBg;
    private javax.swing.JPanel signUpEmailPanel;
    private javax.swing.JPanel signUpPanel;
    private javax.swing.JPanel signUpPasswordPanel;
    private javax.swing.JLabel signUpTitle;
    // End of variables declaration//GEN-END:variables
    class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
    }

}
