/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.interfacetest;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author avery
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        try {
            // Import fonts
            File importTitleFont = new File("src/main/resources/Fonts/Anton-Regular.ttf");
            File importBodyFont = new File("src/main/resources/Fonts/MajorMonoDisplay-Regular.ttf");
            File importAccentFont = new File("src/main/resources/Fonts/OpenSans-Regular.ttf");
            
            // Assign fonts to variables, set font size
            Font titleFont = Font.createFont(Font.TRUETYPE_FONT, importTitleFont).deriveFont(60f);
            Font bodyFont = Font.createFont(Font.TRUETYPE_FONT, importBodyFont).deriveFont(18f);
            Font accentFont = Font.createFont(Font.TRUETYPE_FONT, importAccentFont).deriveFont(14f);
            
            // Set font for UI **BELOW**
            signUpTitle.setFont(titleFont);
            
            confirmSignupButton.setFont(Font.createFont(Font.TRUETYPE_FONT, importAccentFont).deriveFont(18f));
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        backgroundPanel = new javax.swing.JPanel();
        signUpTitle = new javax.swing.JLabel();
        signUpPanel = new RoundedPanel(15, new Color(70,131,166, 200));
        signUpFirstnamePanel = new RoundedPanel(15,new Color(255,225,225));
        firstNameEntryField = new javax.swing.JTextField();
        signupUserIcon = new javax.swing.JLabel();
        signUpPasswordPanel = new RoundedPanel(15,new Color(255,225,225));
        passwordIcon = new javax.swing.JLabel();
        passwordEntryField = new javax.swing.JPasswordField();
        signUpConfirmPasswordPanel = new RoundedPanel(15,new Color(255,225,225));
        confirmPasswordIcon = new javax.swing.JLabel();
        confirmPasswordEntryField = new javax.swing.JPasswordField();
        confirmSignupButton = new javax.swing.JButton();
        signUpLastnamePanel = new RoundedPanel(15, new Color(255,225,225));
        lastNameEntryField = new javax.swing.JTextField();
        signupUserIcon2 = new javax.swing.JLabel();
        signUpUsernamePanel = new RoundedPanel(15, new Color(255,225,225));
        usernameEntryField = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        checkNameButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EduSync - Sign Up");
        setResizable(false);

        backgroundPanel.setBackground(new java.awt.Color(51, 51, 51));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signUpTitle.setFont(new java.awt.Font("Anton", 0, 60)); // NOI18N
        signUpTitle.setForeground(new java.awt.Color(255, 255, 255));
        signUpTitle.setText("SIGN UP");
        backgroundPanel.add(signUpTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        signUpPanel.setForeground(new java.awt.Color(60, 63, 65));
        signUpPanel.setOpaque(false);
        signUpPanel.setPreferredSize(new java.awt.Dimension(400, 506));
        signUpPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signUpFirstnamePanel.setBackground(new java.awt.Color(255, 255, 255));
        signUpFirstnamePanel.setForeground(new java.awt.Color(60, 63, 65));
        signUpFirstnamePanel.setOpaque(false);
        signUpFirstnamePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstNameEntryField.setBackground(new java.awt.Color(0, 0, 0, 1));
        firstNameEntryField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        firstNameEntryField.setForeground(new java.awt.Color(38, 55, 120));
        firstNameEntryField.setBorder(null);
        firstNameEntryField.setOpaque(false);
        signUpFirstnamePanel.add(firstNameEntryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 210, 30));

        signupUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signupIcons/miniUserIconBlue.png"))); // NOI18N
        signUpFirstnamePanel.add(signupUserIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        signUpPanel.add(signUpFirstnamePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 270, 50));

        signUpPasswordPanel.setOpaque(false);
        signUpPasswordPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passwordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signupIcons/passwordBlue.png"))); // NOI18N
        signUpPasswordPanel.add(passwordIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        passwordEntryField.setBackground(new java.awt.Color(0, 0, 0, 1));
        passwordEntryField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        passwordEntryField.setForeground(new java.awt.Color(38, 55, 120));
        passwordEntryField.setBorder(null);
        passwordEntryField.setOpaque(false);
        signUpPasswordPanel.add(passwordEntryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 210, 30));

        signUpPanel.add(signUpPasswordPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 270, 50));

        signUpConfirmPasswordPanel.setOpaque(false);
        signUpConfirmPasswordPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        confirmPasswordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signupIcons/passwordBlue.png"))); // NOI18N
        signUpConfirmPasswordPanel.add(confirmPasswordIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        confirmPasswordEntryField.setBackground(new java.awt.Color(0, 0, 0, 1));
        confirmPasswordEntryField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        confirmPasswordEntryField.setForeground(new java.awt.Color(38, 55, 120));
        confirmPasswordEntryField.setBorder(null);
        confirmPasswordEntryField.setOpaque(false);
        signUpConfirmPasswordPanel.add(confirmPasswordEntryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 210, 30));

        signUpPanel.add(signUpConfirmPasswordPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 270, 50));

        confirmSignupButton.setBackground(new java.awt.Color(56, 182, 255));
        confirmSignupButton.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        confirmSignupButton.setForeground(new java.awt.Color(255, 255, 255));
        confirmSignupButton.setText("Confirm");
        confirmSignupButton.setBorderPainted(false);
        confirmSignupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmSignupButtonActionPerformed(evt);
            }
        });
        signUpPanel.add(confirmSignupButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 110, 40));

        signUpLastnamePanel.setBackground(new java.awt.Color(255, 255, 255));
        signUpLastnamePanel.setOpaque(false);
        signUpLastnamePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lastNameEntryField.setBackground(new java.awt.Color(0, 0, 0, 1));
        lastNameEntryField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lastNameEntryField.setForeground(new java.awt.Color(38, 55, 120));
        lastNameEntryField.setBorder(null);
        lastNameEntryField.setOpaque(false);
        signUpLastnamePanel.add(lastNameEntryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 210, 30));

        signupUserIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signupIcons/miniUserIconBlue.png"))); // NOI18N
        signupUserIcon2.setText("jLabel1");
        signUpLastnamePanel.add(signupUserIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        signUpPanel.add(signUpLastnamePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 270, 50));

        signUpUsernamePanel.setBackground(new java.awt.Color(255, 255, 255));
        signUpUsernamePanel.setOpaque(false);
        signUpUsernamePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameEntryField.setBackground(new java.awt.Color(0, 0, 0, 1));
        usernameEntryField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        usernameEntryField.setForeground(new java.awt.Color(38, 55, 120));
        usernameEntryField.setBorder(null);
        usernameEntryField.setOpaque(false);
        signUpUsernamePanel.add(usernameEntryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 4, 150, 30));

        signUpPanel.add(signUpUsernamePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 160, 40));

        firstNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        firstNameLabel.setText("First Name");
        signUpPanel.add(firstNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Last Name");
        signUpPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username");
        signUpPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        checkNameButton.setBackground(new java.awt.Color(56, 182, 255));
        checkNameButton.setForeground(new java.awt.Color(255, 255, 255));
        checkNameButton.setText("Check name");
        checkNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNameButtonActionPerformed(evt);
            }
        });
        signUpPanel.add(checkNameButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 100, 40));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password");
        signUpPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Confirm Password");
        signUpPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        backgroundPanel.add(signUpPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 370, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signupIcons/bgImage.png"))); // NOI18N
        backgroundPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmSignupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmSignupButtonActionPerformed
        // TODO add your handling code here:
        String signupFirstName = firstNameEntryField.getText();
        String signupLastName = lastNameEntryField.getText();
        String signupUsername = usernameEntryField.getText();
        
        String signupPassword = passwordEntryField.getText();
        String signupConfirmPassword = confirmPasswordEntryField.getText();
        
        if(signupFirstName.isEmpty()||signupLastName.isEmpty()||signupUsername.isEmpty()||signupPassword.isEmpty()||signupConfirmPassword.isEmpty()){
            JOptionPane.showMessageDialog(null, "Empty fields detected. Please fill out all the fields", "Empty Fields", JOptionPane.WARNING_MESSAGE);
        }else if(signupPassword.equals(signupConfirmPassword)){
            try {
                Class.forName("org.postgresql.Driver");
                Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/UserLogin", "Admin", "user123");
                String sqlquery = "INSERT INTO login.login_credentials (last_name, first_name, username, userpassword) VALUES ('"+signupFirstName+"','"+signupLastName+"','"+signupUsername+"','"+signupConfirmPassword+"')";
                PreparedStatement pst = conn.prepareStatement(sqlquery);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Registration Successful");
                LoginPage loginPage = new LoginPage();
                this.dispose();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }else{
            System.out.println(signupPassword);
            System.out.println(signupConfirmPassword);
            JOptionPane.showMessageDialog(null, "Error", "Password does not match",  JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_confirmSignupButtonActionPerformed

    private void checkNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNameButtonActionPerformed
        // TODO add your handling code here:
        String username = usernameEntryField.getText();
        try {
            Class.forName("org.postgresql.Driver");
            Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/UserLogin", "Admin", "user123");
            String sqlquery = "SELECT * FROM login.login_credentials WHERE username='"+username+"'";
            PreparedStatement pst = conn.prepareStatement(sqlquery);
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Username already exists", "Check Username", JOptionPane.WARNING_MESSAGE);
            }else  {
                JOptionPane.showMessageDialog(null, "Username available!", "Check Username", JOptionPane.INFORMATION_MESSAGE);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Username already exists.", "Username Unavailable", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_checkNameButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton checkNameButton;
    private javax.swing.JPasswordField confirmPasswordEntryField;
    private javax.swing.JLabel confirmPasswordIcon;
    private javax.swing.JButton confirmSignupButton;
    private javax.swing.JTextField firstNameEntryField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField lastNameEntryField;
    private javax.swing.JPasswordField passwordEntryField;
    private javax.swing.JLabel passwordIcon;
    private javax.swing.JPanel signUpConfirmPasswordPanel;
    private javax.swing.JPanel signUpFirstnamePanel;
    private javax.swing.JPanel signUpLastnamePanel;
    private javax.swing.JPanel signUpPanel;
    private javax.swing.JPanel signUpPasswordPanel;
    private javax.swing.JLabel signUpTitle;
    private javax.swing.JPanel signUpUsernamePanel;
    private javax.swing.JLabel signupUserIcon;
    private javax.swing.JLabel signupUserIcon2;
    private javax.swing.JTextField usernameEntryField;
    // End of variables declaration//GEN-END:variables
    class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
    }

}
